spring:
  application:
    name: eurakaserver
  config:
    import: optional:configserver:http://localhost:8071/

# Actuaror related
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
